config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  root 'static_pages#home'
	get 'testing', to: 'static_pages#testing'
  get 'faq', to: 'static_pages#faq'
	get 'inlocation', to: 'locations#inlocation'

  resources :states

  resources :towns do
    collection do
      post :import
    end
  end

  resources :clinics do
    collection do
      post :import
    end
  end

  resources :locations do
    collection do
      post :import
    end
  end
end

app/models/clinic.rb
class Clinic < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :lab, presence: true
  validates :addr1, presence: true, uniqueness: { scope: :city, case_sensitive: false }
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :phone, presence: true

  default_scope -> { order(state: :asc)}
  # default_scope -> { order(id: :asc)}

  def street_addr
    [addr1, addr2].compact.join(" , ")
  end

  def city_state
    "#{city}, #{state}"
  end

  def address
    [street_addr, city_state, zip].compact.join(" , ")
  end

  def full_address
    "#{street_addr}" + "\n" + "#{city_state} #{zip}" + "\n"
  end

  def address_changed?
    addr1_changed? || addr2_changed? || city_changed? || state_changed? || zip_changed?
  end

 	def self.import(file)
    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      clinic = find_by(addr1: row["addr1"]) || new
      clinic.attributes = row.to_hash
      clinic.save!
    end
  end


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |clinic|
        csv << clinic.attributes.values
      end
    end
  end
end

# rake geocode:all CLASS=Clinic SLEEP=0.25 BATCH=100

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
	before_action :set_clinic, only: [:edit, :show, :update, :destroy]

	def index
		@clinics = if params[:l]
	    sw_lat, sw_lng, ne_lat, ne_lng = params[:l].split(",")
	    center   = Geocoder::Calculations.geographic_center([[sw_lat, sw_lng], [ne_lat, ne_lng]])
	    distance = Geocoder::Calculations.distance_between(center, [sw_lat, sw_lng])
	    box      = Geocoder::Calculations.bounding_box(center, distance)
	    Clinic.within_bounding_box(box)
	  elsif params[:near]
	    Clinic.near(params[:near])
	  else
	    Clinic.all
		end
		@clinics = @clinics.paginate(:page => params[:page], :per_page => 10)

		# @clinics = Clinic.order(:state)
		respond_to do |format|
		  format.html
		  format.csv { send_data @clinics.to_csv }
		end
	end

	def import
	  Clinic.import(params[:file])
	  redirect_to clinics_path, notice: 'Clinics imported.'
	end

	def show
	end

	def new
    @clinic = Clinic.new
	end

	def create
		@clinic = Clinic.new(clinic_params)
		if @clinic.save
		  flash[:success] = "Clinic was successfully created"
	    redirect_to clinics_path
		else
		  render 'new'
		  flash[:danger] = "Some Clinics were not saved."
		end
	end

	def edit
	end

	def update
		if @clinic.update(clinic_params)
		  flash[:success] = "Clinic was updated successfully"
	    redirect_to clinics_path(@clinic)
		else
		  render 'edit'
		end
	end

	private
		def set_clinic
			@clinic = Clinic.find(params[:id])
		end

		def clinic_params
      params.require(:clinic).permit(:lab, :detail, :addr1, :addr2, :city, :state, :zip, :phone, :ext, :fax, :latitude, :longitude)
    end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_form.html.erb
<%= render 'shared/errors', obj: @clinic %>
<div class="state-form">
  <%= form_for(@clinic, :html => {class: "form-horizontal", role: "form" }) do |f| %>
    <div class="form-group">
      <div class="forminfo">
        <%= f.label :lab %><br>
        <%= f.text_field :lab, class: "form-control", placeholder: "Enter Address", autofocus: true %>
      </div>

      <div class="forminfo">
        <%= f.label :detail %><br>
        <%= f.text_field :detail, class: "form-control", placeholder: "Enter Address", autofocus: true %>
      </div>

      <div class="forminfo">
        <%= f.label :addr1 %><br>
        <%= f.text_field :addr1, class: "form-control", placeholder: "Enter Address", autofocus: true %>
      </div>

      <div class="forminfo">
        <%= f.label :addr2 %><br>
        <%= f.text_field :addr2, class: "form-control", placeholder: "Enter Address", autofocus: true %>
      </div>

      <div class="forminfo">
        <%= f.label :city %><br>
        <%= f.text_field :city, class: "form-control", placeholder: "Enter Address", autofocus: true %>
      </div>

      <div class="forminfo">
        <%= f.label :state %><br>
        <%= f.text_field :state, class: "form-control", placeholder: "Enter Address", autofocus: true %>
      </div>

      <div class="forminfo">
        <%= f.label :zip %><br>
        <%= f.text_field :zip, class: "form-control", placeholder: "Zipcode", autofocus: true %>
      </div>

      <div class="forminfo">
        <%= f.label :phone %><br>
        <%= f.text_field :phone, class: "form-control", placeholder: "Enter Address", autofocus: true %>
      </div>

      <div class="forminfo">
        <%= f.label :ext %><br>
        <%= f.text_field :ext, class: "form-control", placeholder: "Enter Address", autofocus: true %>
      </div>

      <div class="forminfo">
        <%= f.label :fax %><br>
        <%= f.text_field :fax, class: "form-control", placeholder: "Enter Address", autofocus: true %>
      </div>

      <div class="forminfo">
        <%= f.label :latitude %><br>
        <%= f.text_field :latitude, class: "form-control", placeholder: "Enter Address", autofocus: true %>
      </div>

      <div class="forminfo">
        <%= f.label :longitude %><br>
        <%= f.text_field :longitude, class: "form-control", placeholder: "Enter Address", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit(@clinic.new_record? ? "Add Clinic" : "Update Clinic", class: "btn btn-primary") %>
      </div>
    </div>
  <% end %>
</div>

app/views/clinics/edit.html.erb
<% @page_title = "Edit Clinic" %>

<div class="full">
	<div class="wrap">
		<h1><%= @page_title %></h1>
		<%= render 'form' %>
    <%= link_to "Delete This Clinic", clinic_path(@clinic), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-primary btn-danger" %>
		<%= link_to("Cancel", clinic_path(@clinic), :class => 'back-link inline') %>
	</div>
</div>

app/views/clinics/index.html.erb
<% @page_title = "All Testing Clinics" %>

<!-- rake geocode:all CLASS=Clinic SLEEP=0.25 BATCH=50 -->
<div class="full">
	<div class="wrap-lg">
		<div class="col-md-6">
			<h1><%= @page_title %></h1>
		</div>

		<div class="col-md-3 col-md-offset-3">
			<br><br>
		  <% if current_user.admin? %>
			<%= link_to "Add New Clinics", new_clinic_path, class: "btn btn-default" %>
			<% end %>
		</div>
		<div class="clearfix"></div><br>
		<hr>
			<%= form_with(url: clinics_path, class: "form-inline", local: true, method: :get) do |f| %>
			  <%= f.text_field :near, class: "form-control", placeholder: "Search" %>
			  <%= f.submit "Search", class: "btn btn-default search" %>
			<% end %>
		<hr>

		<div class="map-box">
			<%= tag.div nil, id: 'map', data: { clinics: @clinics.to_json(methods: [:address]), l: params[:l] } %>
			<%= link_to "Redo search in this area", "#", id: "redo-search" %>
		</div>

		<div class="clinics-list">
			<table class="clinics-table">
				<tbody>
					<% @clinics.each do |clinic| %>
					<tr>
						<td class="id">
							<p><%= clinic.id %>.</p>
						</td>

						<td class="st-addr">
							<%= simple_format(clinic.full_address.titleize) %>
							<% if clinic.longitude && clinic.latitude %>
								<p>[ <%= clinic.latitude %>,<%= clinic.longitude %> ]</p>
							<% end %>
						</td>

						<td class="number">
							<p><small>Phone:</small><br><%= clinic.phone %>
							<% if clinic.ext %><br>Ext: <%= clinic.ext %> <% end %>
							</p>
						</td>

						<td class="fax">
							<p><small>Fax:</small><br> <%= clinic.fax %></p>
						</td>

						<td class="lab">
							<p><%= clinic.lab %></p>
							<% if clinic.detail %><p><%= clinic.detail %> </p><% end %>
						</td>

						<td class="btns">
							<div class="actions">
								<%= link_to("View", clinic_path(clinic), class: 'action show') %>
							  <% if current_user.admin? %><%= link_to("Edit", edit_clinic_path(clinic), class: 'action edit') %><% end %>
							</div>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<%= will_paginate @clinics, remote: true %>
		</div>
	</div>
</div>


<!--
	IF YOU WANT TO DOWNLOAD CSV
<table class="clinics-table">
	<tbody>
		<% @clinics.each do |clinic| %>
		<tr>
			<td><%= clinic.lab %></td>
			<td><%= clinic.detail %> </td>
			<td><%= clinic.addr1 %></td>
			<td><%= clinic.addr2 %></td>
			<td><%= clinic.city %></td>
			<td><%= clinic.state %></td>
			<td><%= clinic.zip %></td>
			<td><%= clinic.phone %></td>
			<td><%= clinic.ext %></td>
			<td><%= clinic.fax %></td>
			<td><%= clinic.latitude %></td>
			<td><%= clinic.longitude %></td>
		</tr>
		<% end %>
	</tbody>
</table> -->

app/views/clinics/new.html.erb
<% @page_title = "Create a New Clinic" %>

<div class="full">
	<div class="wrap">
		<h1><%= @page_title %></h1>
		<hr><div class="clearfix"></div><br>

		<div class="col-md-6 col-md-offset-6">
			<h3>Import Locations</h3>
			<%= form_tag import_clinics_path, multipart: true do %>
			  <%= file_field_tag :file %>
			  <br>
			  <%= submit_tag "Import" %>
			<% end %>
		</div>
		<div class="clearfix"></div><br>
		<hr>


		<%= render 'form' %>
	</div>
</div>

app/views/clinics/show.html.erb
<% @page_title = 'Clinic' %>

<div class="full">
	<div class="wrap">
	  <h1>Clinic</h1>
	  <hr class="title-line">
		<div class="clearfix"></div>
		<%= link_to "Delete This clinic", clinic_path(@clinic), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-danger" %>
		<%= link_to("Add New clinic", new_clinic_path, :class => 'action new btn-add inline') %>
	</div>
	<div class="clearfix"></div>
</div>