config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  root 'static_pages#home'
	get 'testing', to: 'static_pages#testing'
  get 'faq', to: 'static_pages#faq'
	get 'inlocation', to: 'locations#inlocation'

  resources :states

  resources :towns do
    collection do
      post :import
    end
  end

  resources :clinics do
    collection do
      post :import
    end
  end

  resources :locations do
    collection do
      post :import
    end
  end
end

app/models/state.rb
class State < ApplicationRecord
	validates :name, presence: true
	validates :abv, presence: true
	has_many :towns, dependent: :destroy

  default_scope -> { order(name: :asc)}
	# State.find_each(&:save)
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
	before_action :set_state, only: [ :edit, :update, :destroy, :show]

	def index
		@states = State.all
	end

	def show
		@state_towns = @state.towns.all
	end

	def new
    @state = State.new
	end

	def create
    @state = State.new(state_params)
    if @state.save
      flash[:success] = "State was successfully created"
      redirect_to state_path(@state)
    else
      render 'new'
    end
	end

	def edit
	end

	def update
		if @state.update(state_params)
		  flash[:success] = "State was updated successfully"
      redirect_to state_path(@state)
		else
		  render 'edit'
		end
	end

	def destroy
		State.find(params[:id]).destroy
  	flash[:success] = "State was successfully deleted!"
    redirect_to states_path
	end

	private
		def set_state
			@state = State.find(params[:id])
		end

		def state_params
      params.require(:state).permit(:name, :abv)
    end
end

app/views/states/index.html.erb
<% @page_title = "State Testing Locations" %>

<div class="full">
	<div class="wrap">
		<h1><%= @page_title %></h1>
		<!-- <p>Get DNA Tested Today provides affordable DNA/Paternity Testing in over 2500 locations nationwide. Each of our locations are certified and accredited by the AABB and ISO 17025.</p> -->


		<div class="newlist">
			<h2>Choose a state from the list below to find a location near you.</h2>
			<div class="states-dd">
				<div class="dropdown">
				  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				    Select a State <i class="fa fa-angle-down"></i>
				  </button>

				  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
						<% for state in @states %>
						 	<%= link_to state_path(state), class: 'dropdown-item' do %>
								<%= state.id %>. <%= state.name %>
						 	<% end %>
					  <% end %>

				  </div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- state26 = State.create(name: "Nebraska", abv: "NE") -->
<!-- .each do |state|  -->
<!-- for state in @cols_one  -->

app/views/states/show.html.erb
<% @page_title = @state.name.capitalize %>

<div class="full pop">
	<div class="one">
	  <h1><span><%= @state.name %></span></h1>
		<%= link_to("Back to States", states_path, :class => 'back-link') %>
	</div>

	<div class="location-map">

		<% if @state_towns.count != 0 %>
			<div class="map-hlf">
				 <!-- render 'shared/map'  -->
  		</div>

  		<div class="town-hlf">
  			<div class="search-sec">
					<div class="searcher">
						<!--  form_with(url: locations_path, class: "form-inline", local: true, method: :get) do |f|
						  = f.text_field :near, class: "form-control", placeholder: "Search"
						  = f.submit "", class: "btn btn-outline-secondary search"
						 end  -->
					</div>
				</div>


				<div class="loclist">
					<table class="listing">
						<% @state_towns.each do |town| %>
							<tr>
								<% if user_signed_in? && current_user.admin? %>
								  <td><h4 class="state-name"><%= town.id %>.&nbsp; <%= link_to town.townname.capitalize, town_path(town) %></h4></td>
						   <% else %>
							   <td><h4 class="state-name"><%= link_to town.townname.capitalize, town_path(town) %></h4></td>
						   <% end %>
						  </tr>
			  		<% end %>
					</table>
				</div>
			</div>

  		<% else %>
			 	<p>Unfortunately, we have no testing locations in <%= @state.name %>, but you can still follow the link below, and order an At Home DNA Test Kit Today!</p>
			<% end %>
	</div>
</div>