config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  root 'static_pages#home'
	get 'testing', to: 'static_pages#testing'
  get 'faq', to: 'static_pages#faq'
	get 'inlocation', to: 'locations#inlocation'

  resources :states

  resources :towns do
    collection do
      post :import
    end
  end

  resources :clinics do
    collection do
      post :import
    end
  end

  resources :locations do
    collection do
      post :import
    end
  end
end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="col-md-12">
    <div class="panel panel-danger err">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error") %>
          prohibited this <%= obj.class %> from being saved:
        </h2>

        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_map.html.erb
<%= tag.div nil, id: 'map', data: { locations: @locations.to_json(methods: [:address]), l: params[:state] } %>
<%= link_to "Redo search in this area", "#", id: "redo-search" %>

app/views/shared/_sidebar.html.erb
<div class="side-bar">
  <nav class="menu">
		<ul class="side-menu">
			<li><%= link_to 'Home', root_path, class: 'sm-link' %></li>
			<li><%= link_to 'Testing', testing_path, class: 'sm-link' %></li>
			<!-- <li><%= link_to 'States', states_path, class: 'sm-link' %></li> -->
			<!-- <li><%= link_to 'Clinics', clinics_path, class: 'sm-link' %></li> -->
			<li><%= link_to 'Locations', locations_path, class: 'sm-link' %></li>
			<li><%= link_to "FAQ's", faq_path, class: 'sm-link' %></li>
			<div class="clearfix"></div>
			<br><br><hr><br>
		  <% if current_user.try(:admin?) %> 
				<!-- <p><small><b>Download:</small></p> -->
				<%= link_to "Download CSV", locations_path(format: "csv"), class: 'btn btn-default dl' %> 
				<div class="clearfix"></div><br>
			  <%= link_to "Excel", locations_path(format: "xls"), class: 'btn btn-default dl' %>
			<% end %> 
		</ul>
  </nav>
</div>

app/views/shared/_topbar.html.erb
<div class="topbar">
  <div class="inside">
    <div class="logo-block"><%= link_to(image_tag( 'dna-logo.png', alt: 'Get DNA Tested Today logo', class: 'img-responsive logo'), root_path ) %></div>

		<% if user_signed_in? %>
			<div class="user-access-block">
				<div class="uk-inline">
				    <a class="uk-button" type="button">
							<h4><%= "#{current_user.name}" %></h4>
				    </a>

				    <div uk-drop="mode: click" class="cst">
				        <ul class="uk-card uk-card-body uk-card-default">
				        	<!-- <li class="nav-li ft-only"><%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %></li>
				        	<li class="nav-li ft-only"><%= link_to 'Log In', new_user_session_path, class: 'nav-link' %></li>-->
				        	<li class="nav-li"><%= link_to "#{current_user.name}*", edit_user_registration_path, class: 'nav-link' %></li>
				        	<li class="nav-li"><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
				        </ul>
				    </div>
				</div>
			</div>
		<% end %>

		<div class="uk-inline mobile-menu">
	    <a class="uk-button" type="button">
				<h4>Menu</h4>
	    </a>

	    <div uk-drop="mode: click" class="cst">
        <ul class="uk-card uk-card-body uk-card-default">
					<li><%= link_to 'Home', root_path, class: 'sm-link' %></li>
					<li><%= link_to 'Testing', testing_path, class: 'sm-link' %></li>
					<li><%= link_to 'Locations', locations_path, class: 'sm-link' %></li>
					<li><%= link_to "FAQ's", faq_path, class: 'sm-link' %></li>
        	<li class="nav-li"><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
        </ul>
      </div>
    </div>

  </div>
</div>