config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  root 'static_pages#home'
	get 'testing', to: 'static_pages#testing'
  get 'faq', to: 'static_pages#faq'
	get 'inlocation', to: 'locations#inlocation'

  resources :states

  resources :towns do
    collection do
      post :import
    end
  end

  resources :clinics do
    collection do
      post :import
    end
  end

  resources :locations do
    collection do
      post :import
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :lab, presence: true
  validates :addr1, presence: true, uniqueness: { scope: :zip, case_sensitive: false }
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :phone, presence: true

  # default_scope -> { order(state: :asc)}

  def street_addr
    "#{addr1}" + "\n" + "#{addr2}"
  end

  def city_state
    "#{city}, #{state}"
  end

  def address
    [street_addr, city_state, zip].compact.join(" , ")
  end

  def full_address
    "#{street_addr}" + "\n" + "#{city_state} #{zip}" + "\n"
  end

  def address_changed?
    addr1_changed? || addr2_changed? || city_changed? || state_changed? || zip_changed?
  end

  def ad_zip
    "#{addr1}, #{zip}"
  end

  def self.import(file)
    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      location = find_by(addr1: row["addr1"]) || new
      location.attributes = row.to_hash
      location.save!
    end
  end


  def self.to_csv(options = {})
    desired_columns = ["lab", "detail", "addr1", "addr2", "city", "state", "zip", "phone", "ext", "fax", "latitude", "longitude"]
    CSV.generate(options) do |csv|
      csv << desired_columns
      all.each do |location|
        csv << location.attributes.values_at(*desired_columns)
      end
    end
  end

end

# rake geocode:all CLASS=Location SLEEP=0.25 BATCH=100

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_action :set_location, only: [:edit, :show, :update, :destroy]

	def index
		@locations = if params[:l]
	    sw_lat, sw_lng, ne_lat, ne_lng = params[:l].split(",")
	    center   = Geocoder::Calculations.geographic_center([[sw_lat, sw_lng], [ne_lat, ne_lng]])
	    distance = Geocoder::Calculations.distance_between(center, [sw_lat, sw_lng])
	    box      = Geocoder::Calculations.bounding_box(center, distance)
	    Location.within_bounding_box(box)
	  elsif params[:near]
	    Location.near(params[:near], 100)
	  else
	    Location.all
		end
		# @locations = @locations.paginate(:page => params[:page], :per_page => 40)
		# @locations = Location.all

		respond_to do |format|
		  format.html
		  format.csv { send_data @locations.to_csv }
		  format.xls
		end



		# @states = Location.distinct.pluck(:state)
		# @states = Location.pluck(:state)
		# @all_states = Location.distinct.select(:state).map { |s| s.state }
	end

	def inlocation
		@locations = Location.all
		@all_zips = Location.distinct.select(:zip).map { |s| s.zip }
		@all_adds = Location.distinct.select(:addr1).map { |a| a.addr1 }
	end

	def import
	  Location.import(params[:file])
	  redirect_to locations_path, notice: 'Locations imported.'
	end

	def show
	end

	def new
    @location = Location.new
	end

	def create
		@location = Location.new(location_params)
		if @location.save
		  flash[:success] = "Location was successfully created"
	    redirect_to locations_path
		else
		  render 'new'
		  flash[:danger] = "Some Locations were not saved."
		end
	end

	def edit
	end

	def update
		if @location.update(location_params)
		  flash[:success] = "Location was updated successfully. You may close this tab."
	    redirect_to locations_path
		else
		  render 'edit'
		end
	end

	def destroy
		Location.find(params[:id]).destroy
  	flash[:success] = "Location was successfully deleted!"
    redirect_to locations_path
	end

	private
		def set_location
			@location = Location.find(params[:id])
		end

		def location_params
      params.require(:location).permit(:lab, :detail, :addr1, :addr2, :city, :state, :zip, :phone, :ext, :fax, :latitude, :longitude)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= render 'shared/errors', obj: @location %>
<div class="state-form">
  <%= form_for(@location, :html => {class: "form-horizontal", role: "form" }) do |f| %>
    <div class="form-group">
      <div class="forminfo">
        *<%= f.label :location_lab %>:<br>
        <%= f.text_field :lab, class: "form-control", placeholder: "Lab Corp", autofocus: true %>
      </div>

      <div class="forminfo">
        <%= f.label :Location_notes %>:<br>
        <%= f.text_field :detail, class: "form-control", placeholder: "*Must have appointment", autofocus: true %>
      </div>

      <div class="forminfo inline hlf uno">
        *<%= f.label :street_address %>:<br>
        <%= f.text_field :addr1, class: "form-control", placeholder: "123 Main St", autofocus: true %>
      </div>

      <div class="forminfo inline hlf">
        <%= f.label :street_address_2 %>:<br>
        <%= f.text_field :addr2, class: "form-control", placeholder: "Suite 488", autofocus: true %>
      </div>

      <div class="forminfo inline uno">
        *<%= f.label :city %>:<br>
        <%= f.text_field :city, class: "form-control", placeholder: "Gulf Shores", autofocus: true %>
      </div>

      <div class="forminfo inline">
        *<%= f.label :state %>:<br>
        <%= f.text_field :state, class: "form-control", placeholder: "Al", autofocus: true %>
      </div>

      <div class="forminfo inline">
        *<%= f.label :zip %>:<br>
        <%= f.text_field :zip, class: "form-control", placeholder: "36542", autofocus: true %>
      </div>

      <div class="forminfo inline uno">
        *<%= f.label :phone %>:<br>
        <%= f.text_field :phone, class: "form-control", placeholder: "1234567890", autofocus: true %>
      </div>

      <div class="forminfo inline">
        <%= f.label :ext %>:<br>
        <%= f.text_field :ext, class: "form-control", placeholder: "1", autofocus: true %>
      </div>

      <div class="forminfo inline">
        <%= f.label :fax %>:<br>
        <%= f.text_field :fax, class: "form-control", placeholder: "1234567890", autofocus: true %>
      </div>

      <div class="forminfo inline uno">
        <%= f.label :latitude %>:<br>
        <%= f.text_field :latitude, class: "form-control", placeholder: "Latitude", autofocus: true %>
      </div>

      <div class="forminfo inline">
        <%= f.label :longitude %>:<br>
        <%= f.text_field :longitude, class: "form-control", placeholder: "Longitude", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="add-update">
        <%= f.submit(@location.new_record? ? "Add Location" : "Update Location", class: "btn btn-primary") %>
        <%= link_to("[ Cancel ]", locations_path, :class => 'back-link inline') %>

        <% unless @location.new_record? %>
          <%= link_to "Delete This Location", location_path(@location), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-primary btn-danger" %>
        <% end %>
      </div>
      <p><small>*Required Fields</small></p>
    </div>
  <% end %>
</div>

app/views/locations/edit.html.erb
<% @page_title = "Edit Location" %>

<div class="full">
	<div class="wrap">

		<div class="form-pagetop">
			<div class="title-left">
				<h1><%= @page_title %></h1>
			</div>
		<div class="clearfix"></div><hr>

		<div class="form-sec">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/locations/index.html.erb
<% @page_title = "All Testing Locations" %>

<!-- rake geocode:all CLASS=Location SLEEP=0.25 BATCH=50 -->
<div class="full all-search">
	<div class="wrap-lg">
		<div class="title-left">
			<h1><%= @page_title %></h1>
		</div>

		<div class="btns-right">
		  <% if current_user.admin? %>
			<%= link_to "Add New Locations", new_location_path, class: "btn btn-default" %>
			<% end %>
		</div>
		<div class="clearfix"></div>

		<hr class="search-border top">
		<%= form_with(url: locations_path, class: "form-inline", local: true, method: :get) do |f| %>
		  <%= f.text_field :near, class: "form-control", placeholder: "Search" %>
		  <%= f.submit "Search", class: "btn btn-default search" %>
		<% end %>
		<hr class="search-border btm">

		<div class="map-box">
			<%= tag.div nil, id: 'map', data: { locations: @locations.to_json(methods: [:address]), l: params[:l] } %>
			<%= link_to "[ Redo search in this area ]", "#", id: "redo-search" %>
			<div class="pag-box map-side">
				<!-- <= will_paginate @locations, remote: true %> -->
			</div>
			<h4 class="loc-count"><%= @locations.size %> Locations</h4>
		</div>

		<div class="locations-list">
			<table class="locations-table">
				<tbody>
					<!-- <div class="pag-box top"><= will_paginate @locations, remote: true %></div> -->
					<div class="clearfix"></div>

					<tr class="toprow">
						<td class="st-addr">
							<p>Address</p>
						</td>

						<td class="number">
							<p>Phone</p>
						</td>

						<td class="fax">
							<p>Fax</p>
						</td>

						<td class="lab">
							<p>Lab/Details</p>
						</td>
					</tr>

					<% @locations.each do |location| %>
					<tr class="results">
						<td class="st-addr">
							<p>
								<%= location.addr1.titleize %><br>
								<% if location.addr2 %><%= location.addr2.titleize %><br><% end %>
								<%= location.city.titleize %>, <%= location.state.upcase %> <%= location.zip %>
							</p>
						</td>

						<td class="number">
							<p>
								<%= number_to_phone(location.phone, delimiter: '.', area_code: true) %>
							<% if location.ext %><br><span class="ext">Ext: <%= location.ext %></span> <% end %>
							</p>
						</td>

						<td class="fax">
							<p>
								<%= number_to_phone(location.fax, delimiter: '.', area_code: true) %></p>
						</td>

						<td class="lab">
							<p><%= location.lab %>
								<% if location.detail %><br><span class="dets"><%= location.detail %></span><% end %>
							</p>
						</td>

						<td class="btns">
							<div class="actions">
								<% if current_user.admin? %>
									<%= link_to("[View]", location_path(location), class: 'action view') %>
								  <%= link_to("[Edit]", edit_location_path(location), class: 'action edit', target: "_blank") %>
							  <% end %>
							</div>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<!-- <div class="pag-box btm"><= will_paginate @locations, remote: true %></div> -->
		</div>
	</div>
</div>

app/views/locations/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Lab</Data></Cell>
        <Cell><Data ss:Type="String">Detail</Data></Cell>
        <Cell><Data ss:Type="String">Address</Data></Cell>
        <Cell><Data ss:Type="String">Address 2</Data></Cell>
        <Cell><Data ss:Type="String">City</Data></Cell>
        <Cell><Data ss:Type="String">State</Data></Cell>
        <Cell><Data ss:Type="String">Zip</Data></Cell>
        <Cell><Data ss:Type="String">Phone</Data></Cell>
        <Cell><Data ss:Type="String">Fax</Data></Cell>
        <Cell><Data ss:Type="String">Latitude</Data></Cell>
        <Cell><Data ss:Type="String">Longitude</Data></Cell>
      </Row>
    <% @locations.each do |location| %>
      <Row>
        <Cell><Data ss:Type="String"><%= location.lab %></Data></Cell>
        <Cell><Data ss:Type="String"><%= location.detail %></Data></Cell>
        <Cell><Data ss:Type="String"><%= location.addr1 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= location.addr2 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= location.city %></Data></Cell>
        <Cell><Data ss:Type="String"><%= location.state %></Data></Cell>
        <Cell><Data ss:Type="String"><%= location.zip %></Data></Cell>
        <Cell><Data ss:Type="String"><%= location.phone %></Data></Cell>
        <Cell><Data ss:Type="String"><%= location.ext %></Data></Cell>
        <Cell><Data ss:Type="String"><%= location.fax %></Data></Cell>
        <Cell><Data ss:Type="Float"><%= location.latitude %></Data></Cell>
        <Cell><Data ss:Type="Float"><%= location.longitude %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/locations/inlocation.html.erb
<% @page_title = "All Testing Locations" %>

<!-- rake geocode:all CLASS=Location SLEEP=0.25 BATCH=50 -->
<div class="full all-search">
	<div class="wrap-lg">
		<div class="locations-list">
			<table class="locations-table">
				<tbody>
					<div class="clearfix"></div>

					<tr class="toprow">
						<th class="id"><p>ID</p></th>
						<th class="st-addr">
							<p>Address</p>
						</th>

						<th class="number">
							<p>City</p>
						</th>

						<th class="fax">
							<p>Zip</p>
						</th>

						<th class="lab">
							<p>Phone</p>
						</th>
					</tr>


          <% tag = 0 %>
          <p><b>All Zips:</b> <%= @locations.count %><br>
          <b>Unique Zips:</b> <%= @all_zips.count %></p>

          <p>
          	<b>Addresses:</b> <%= @locations.count %><br>
          	<b>Unique:</b> <%= @all_adds.count %>
          </p>

					<br><br><br>

					<% @locations.each do |location| %>
					<tr class="results">
						<td class="btns">
									<%= link_to("[View]", location_path(location), class: 'action view') %>

						</td>
						<td class="st-addr">
							<p>
								<%= location.addr1.titleize %> &nbsp;<b><% if location.addr2 %><%= location.addr2.titleize %></b><% end %>
							</p>
						</td>

						<td>
							<p><%= location.city_state.titleize %></p>
						</td>

						<td>
							<p> <%= location.zip %></p>
						</td>

						<td class="number">
							<p>
								<%= number_to_phone(location.phone, delimiter: '.', area_code: true) %>
							<% if location.ext %><br><span class="ext">Ext: <%= location.ext %></span> <% end %>
							</p>
						</td>

						<!-- <td class="fax">
							<p>
								<%= number_to_phone(location.fax, delimiter: '.', area_code: true) %></p>
						</td>

						<td class="lab">
							<p><%= location.lab %>
								<% if location.detail %><br><span class="dets"><%= location.detail %></span><% end %>
							</p>
						</td> -->
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/locations/new.html.erb
<% @page_title = "Create a New Location" %>

<div class="full">
	<div class="wrap">
		<div class="form-pagetop">
			<div class="title-left">
				<h1><%= @page_title %></h1>
			</div>

			<% if current_user.email = "kelli@hsdesignhouse.com"%>
			<div class="btns-right">
				<div class="import-box">
					<h4>Import Multiple Locations</h4>
					<hr class="hlf">
					<%= form_tag import_locations_path, multipart: true do %>
					  <%= file_field_tag :file %>
					  <br>
					  <%= submit_tag "Import", class: 'submit' %>
					<% end %>
				</div>
			</div>
			<% end %>
		</div>
		<div class="clearfix"></div><hr>

		<div class="form-sec">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/locations/show.html.erb
<% @page_title = 'Location' %>

<div class="full">
	<div class="wrap">
	  <h1>Location Info</h1>
	  <hr class="title-line">
		<div class="clearfix"></div>

		<div class="full-location-info">
			<div class="attr lab">
				<p>
					<b>Lab:</b><br>
					<%= @location.lab %>
				</p>
			</div>

			<div class="attr details">
				<p>
					<b>Notes/Details:</b><br>
					<% if @location.detail %>
						<%= @location.detail %>
					<% else %>
					...
					<% end %>
				</p>
			</div>

			<div class="attr st-addr">
				<p>
					<b>Address:</b><br>
					<%= @location.addr1.titleize %><br>
					<% if @location.addr2 %><%= @location.addr2.titleize %><br><% end %>
					<%= @location.city.titleize %>, <%= @location.state.upcase %> <%= @location.zip %>
				</p>

				<% if @location.longitude && @location.latitude %>
					<p>[ <%= @location.latitude %>,<%= @location.longitude %> ]</p>
				<% end %>
			</div>

			<div class="attr number">
				<p>
					<b>Phone:</b><br>
					<%= number_to_phone(@location.phone, delimiter: '.', area_code: true) %>
				<% if @location.ext %><br><span class="ext">Ext: <%= @location.ext %></span> <% end %>
				</p>
			</div>

			<div class="attr fax">
				<p>
					<b>Fax:</b><br>
					<%= number_to_phone(@location.fax, delimiter: '.', area_code: true) %></p>
			</div>
		</div>

		<div class="location-actions">
			<% if current_user.admin? %>
			  <%= link_to("Edit Location", edit_location_path(@location), class: 'action btn btn-default edit') %>
				<%= link_to "Delete Location", location_path(@location), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "action btn btn-danger" %>
			<% end %>

			<%= link_to("<< All Locations", locations_path, :class => 'action btn btn-default back') %>
		</div>

	</div>
</div>